# Generated by Django 4.2.8 on 2024-01-13 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_booked_on_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('emergency_type', models.CharField(choices=[('loss', '物品遗失'), ('damage', '设施损坏'), ('accident', '意外事故'), ('other', '其他')], max_length=10)),
                ('description', models.TextField()),
                ('reported_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
