# Generated by Django 4.2.8 on 2024-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='other', max_length=6),
        ),
    ]
